### ISSUE TITLE
Broken with arq v0.23a1

### ISSUE THREAD

**Issue by AngellusMortis** [SlavaSkvortsov/arq-django-admin#3]
The latest version of arq (`v0.23a1`) switch from using `aioredis` to using `redis.asyncio` in the upcoming redis-py v4.2.0. This is causing the following stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/arq_admin/redis.py", line 11, in get_redis
    yield redis
  File "/usr/local/lib/python3.10/site-packages/arq_admin/queue.py", line 56, in get_stats
    job_ids = set(await redis.zrangebyscore(self.name))
TypeError: SortedSetCommands.zrangebyscore() missing 2 required positional arguments: 'min' and 'max'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "/usr/local/lib/python3.10/site-packages/arq_admin/views.py", line 21, in get_queryset
    return asyncio.run(self._gather_queues())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/arq_admin/views.py", line 37, in _gather_queues
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.10/site-packages/arq_admin/queue.py", line 55, in get_stats
    async with get_redis(self.redis_settings) as redis:
  File "/usr/local/lib/python3.10/contextlib.py", line 217, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/arq_admin/redis.py", line 14, in get_redis
    await redis.wait_closed()
AttributeError: 'ArqRedis' object has no attribute 'wait_closed'
```

Reference: https://github.com/samuelcolvin/arq/issues/250

**Comment by SlavaSkvortsov** [comment]
Hi! Thank you for reporting the issue. I'll take a look on it during this weekend

**Comment by AngellusMortis** [comment]
I might submit a PR. I already have it working in my local. Working on adding log output from the jobs to the admin page (that is a huge maybe on if I want to contribute it, the way I am gathering logs is really hacky).

**Comment by AngellusMortis** [comment]
v0.23 is now fully released.

**Comment by SlavaSkvortsov** [comment]
Yeah, sorry for being lazy ass :((( 

I'll release it this week
